// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Multiplication.proto

package proxy;

public final class MultiplicationOuterClass {
  private MultiplicationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultiRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MultiRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 nombre = 1;</code>
     */
    int getNombre();

    /**
     * <code>int32 limite = 2;</code>
     */
    int getLimite();
  }
  /**
   * Protobuf type {@code MultiRequest}
   */
  public  static final class MultiRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MultiRequest)
      MultiRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiRequest.newBuilder() to construct.
    private MultiRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiRequest() {
      nombre_ = 0;
      limite_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nombre_ = input.readInt32();
              break;
            }
            case 16: {

              limite_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proxy.MultiplicationOuterClass.internal_static_MultiRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proxy.MultiplicationOuterClass.internal_static_MultiRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proxy.MultiplicationOuterClass.MultiRequest.class, proxy.MultiplicationOuterClass.MultiRequest.Builder.class);
    }

    public static final int NOMBRE_FIELD_NUMBER = 1;
    private int nombre_;
    /**
     * <code>int32 nombre = 1;</code>
     */
    public int getNombre() {
      return nombre_;
    }

    public static final int LIMITE_FIELD_NUMBER = 2;
    private int limite_;
    /**
     * <code>int32 limite = 2;</code>
     */
    public int getLimite() {
      return limite_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nombre_ != 0) {
        output.writeInt32(1, nombre_);
      }
      if (limite_ != 0) {
        output.writeInt32(2, limite_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nombre_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, nombre_);
      }
      if (limite_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, limite_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proxy.MultiplicationOuterClass.MultiRequest)) {
        return super.equals(obj);
      }
      proxy.MultiplicationOuterClass.MultiRequest other = (proxy.MultiplicationOuterClass.MultiRequest) obj;

      boolean result = true;
      result = result && (getNombre()
          == other.getNombre());
      result = result && (getLimite()
          == other.getLimite());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMBRE_FIELD_NUMBER;
      hash = (53 * hash) + getNombre();
      hash = (37 * hash) + LIMITE_FIELD_NUMBER;
      hash = (53 * hash) + getLimite();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.MultiplicationOuterClass.MultiRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proxy.MultiplicationOuterClass.MultiRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MultiRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultiRequest)
        proxy.MultiplicationOuterClass.MultiRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proxy.MultiplicationOuterClass.internal_static_MultiRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proxy.MultiplicationOuterClass.internal_static_MultiRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proxy.MultiplicationOuterClass.MultiRequest.class, proxy.MultiplicationOuterClass.MultiRequest.Builder.class);
      }

      // Construct using proxy.MultiplicationOuterClass.MultiRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nombre_ = 0;

        limite_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proxy.MultiplicationOuterClass.internal_static_MultiRequest_descriptor;
      }

      @java.lang.Override
      public proxy.MultiplicationOuterClass.MultiRequest getDefaultInstanceForType() {
        return proxy.MultiplicationOuterClass.MultiRequest.getDefaultInstance();
      }

      @java.lang.Override
      public proxy.MultiplicationOuterClass.MultiRequest build() {
        proxy.MultiplicationOuterClass.MultiRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proxy.MultiplicationOuterClass.MultiRequest buildPartial() {
        proxy.MultiplicationOuterClass.MultiRequest result = new proxy.MultiplicationOuterClass.MultiRequest(this);
        result.nombre_ = nombre_;
        result.limite_ = limite_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proxy.MultiplicationOuterClass.MultiRequest) {
          return mergeFrom((proxy.MultiplicationOuterClass.MultiRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proxy.MultiplicationOuterClass.MultiRequest other) {
        if (other == proxy.MultiplicationOuterClass.MultiRequest.getDefaultInstance()) return this;
        if (other.getNombre() != 0) {
          setNombre(other.getNombre());
        }
        if (other.getLimite() != 0) {
          setLimite(other.getLimite());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proxy.MultiplicationOuterClass.MultiRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proxy.MultiplicationOuterClass.MultiRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int nombre_ ;
      /**
       * <code>int32 nombre = 1;</code>
       */
      public int getNombre() {
        return nombre_;
      }
      /**
       * <code>int32 nombre = 1;</code>
       */
      public Builder setNombre(int value) {
        
        nombre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nombre = 1;</code>
       */
      public Builder clearNombre() {
        
        nombre_ = 0;
        onChanged();
        return this;
      }

      private int limite_ ;
      /**
       * <code>int32 limite = 2;</code>
       */
      public int getLimite() {
        return limite_;
      }
      /**
       * <code>int32 limite = 2;</code>
       */
      public Builder setLimite(int value) {
        
        limite_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 limite = 2;</code>
       */
      public Builder clearLimite() {
        
        limite_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MultiRequest)
    }

    // @@protoc_insertion_point(class_scope:MultiRequest)
    private static final proxy.MultiplicationOuterClass.MultiRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proxy.MultiplicationOuterClass.MultiRequest();
    }

    public static proxy.MultiplicationOuterClass.MultiRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiRequest>
        PARSER = new com.google.protobuf.AbstractParser<MultiRequest>() {
      @java.lang.Override
      public MultiRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proxy.MultiplicationOuterClass.MultiRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultiResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MultiResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string resultat = 1;</code>
     */
    java.lang.String getResultat();
    /**
     * <code>string resultat = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultatBytes();
  }
  /**
   * Protobuf type {@code MultiResponse}
   */
  public  static final class MultiResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MultiResponse)
      MultiResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiResponse.newBuilder() to construct.
    private MultiResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiResponse() {
      resultat_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              resultat_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proxy.MultiplicationOuterClass.internal_static_MultiResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proxy.MultiplicationOuterClass.internal_static_MultiResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proxy.MultiplicationOuterClass.MultiResponse.class, proxy.MultiplicationOuterClass.MultiResponse.Builder.class);
    }

    public static final int RESULTAT_FIELD_NUMBER = 1;
    private volatile java.lang.Object resultat_;
    /**
     * <code>string resultat = 1;</code>
     */
    public java.lang.String getResultat() {
      java.lang.Object ref = resultat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultat_ = s;
        return s;
      }
    }
    /**
     * <code>string resultat = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultatBytes() {
      java.lang.Object ref = resultat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResultatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resultat_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResultatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resultat_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proxy.MultiplicationOuterClass.MultiResponse)) {
        return super.equals(obj);
      }
      proxy.MultiplicationOuterClass.MultiResponse other = (proxy.MultiplicationOuterClass.MultiResponse) obj;

      boolean result = true;
      result = result && getResultat()
          .equals(other.getResultat());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULTAT_FIELD_NUMBER;
      hash = (53 * hash) + getResultat().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proxy.MultiplicationOuterClass.MultiResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proxy.MultiplicationOuterClass.MultiResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MultiResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultiResponse)
        proxy.MultiplicationOuterClass.MultiResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proxy.MultiplicationOuterClass.internal_static_MultiResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proxy.MultiplicationOuterClass.internal_static_MultiResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proxy.MultiplicationOuterClass.MultiResponse.class, proxy.MultiplicationOuterClass.MultiResponse.Builder.class);
      }

      // Construct using proxy.MultiplicationOuterClass.MultiResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        resultat_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proxy.MultiplicationOuterClass.internal_static_MultiResponse_descriptor;
      }

      @java.lang.Override
      public proxy.MultiplicationOuterClass.MultiResponse getDefaultInstanceForType() {
        return proxy.MultiplicationOuterClass.MultiResponse.getDefaultInstance();
      }

      @java.lang.Override
      public proxy.MultiplicationOuterClass.MultiResponse build() {
        proxy.MultiplicationOuterClass.MultiResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proxy.MultiplicationOuterClass.MultiResponse buildPartial() {
        proxy.MultiplicationOuterClass.MultiResponse result = new proxy.MultiplicationOuterClass.MultiResponse(this);
        result.resultat_ = resultat_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proxy.MultiplicationOuterClass.MultiResponse) {
          return mergeFrom((proxy.MultiplicationOuterClass.MultiResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proxy.MultiplicationOuterClass.MultiResponse other) {
        if (other == proxy.MultiplicationOuterClass.MultiResponse.getDefaultInstance()) return this;
        if (!other.getResultat().isEmpty()) {
          resultat_ = other.resultat_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proxy.MultiplicationOuterClass.MultiResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proxy.MultiplicationOuterClass.MultiResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object resultat_ = "";
      /**
       * <code>string resultat = 1;</code>
       */
      public java.lang.String getResultat() {
        java.lang.Object ref = resultat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resultat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string resultat = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultatBytes() {
        java.lang.Object ref = resultat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resultat = 1;</code>
       */
      public Builder setResultat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resultat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resultat = 1;</code>
       */
      public Builder clearResultat() {
        
        resultat_ = getDefaultInstance().getResultat();
        onChanged();
        return this;
      }
      /**
       * <code>string resultat = 1;</code>
       */
      public Builder setResultatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resultat_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MultiResponse)
    }

    // @@protoc_insertion_point(class_scope:MultiResponse)
    private static final proxy.MultiplicationOuterClass.MultiResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proxy.MultiplicationOuterClass.MultiResponse();
    }

    public static proxy.MultiplicationOuterClass.MultiResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiResponse>
        PARSER = new com.google.protobuf.AbstractParser<MultiResponse>() {
      @java.lang.Override
      public MultiResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proxy.MultiplicationOuterClass.MultiResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MultiRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MultiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024Multiplication.proto\".\n\014MultiRequest\022\016" +
      "\n\006nombre\030\001 \001(\005\022\016\n\006limite\030\002 \001(\005\"!\n\rMultiR" +
      "esponse\022\020\n\010resultat\030\001 \001(\t2;\n\016Multiplicat" +
      "ion\022)\n\006calcul\022\r.MultiRequest\032\016.MultiResp" +
      "onse0\001B\007\n\005proxyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MultiRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MultiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MultiRequest_descriptor,
        new java.lang.String[] { "Nombre", "Limite", });
    internal_static_MultiResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MultiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MultiResponse_descriptor,
        new java.lang.String[] { "Resultat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
